name: aq_admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  flutter_custom_clippers: ^1.1.1
  flutter_pdfview: ^1.0.3+5
  font_awesome_flutter: ^8.10.0
  search_page: ^1.3.0
  vertical_tabs: ^0.2.0
  esys_flutter_share: ^1.0.2
  flutter_clean_calendar: ^1.0.2+1
  flutter_staggered_grid_view: ^0.3.2
  progress_dialog: ^1.2.4
  pull_to_refresh: ^1.6.3 
  http_parser: ^3.1.4
  share_extend: ^1.1.5 
  image_picker: ^0.6.7+4 
  file_picker: ^1.13.0
  path_provider: ^1.6.11
  shared_preferences: ^0.5.12+4
  maps_launcher: ^1.2.2+1  
  url_launcher: ^5.5.0
  flutter_swiper: ^1.1.6
  step_progress_indicator: ^0.2.4+7
  photo_view: ^0.10.2
  fluttertoast: ^7.1.1
  firebase_messaging: ^7.0.3
  autocomplete_textfield: ^1.7.3
  percent_indicator: ^3.0.1
  flutter_image_compress: ^1.0.0-nullsafety
  cached_network_image: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/aq_icon_legacy.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/aq_icon_new.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/AQglass.png
    - lib/assets/employee.png
    - lib/assets/Measure_Created.png
    - lib/assets/Measure_Completed.png
    - lib/assets/Measure_incomplete.png
    - lib/assets/Measure_assigned.png
    - lib/assets/Measure_Created.png
    - lib/assets/waiting_delivery.png
    - lib/assets/Waiting_Approval.png
    - lib/assets/Paid.png
    - lib/assets/Needs_payment.png
    - lib/assets/Needs_Install.png
    - lib/assets/Needs_Estimate.png
    - lib/assets/install_incomplete.png
    - lib/assets/install_assigned.png
    - lib/assets/estimate_dormant.png
    - lib/assets/estimate_rejected.png
    - lib/assets/needs_ordering.png
    - lib/assets/Material_ready.png
    - lib/assets/unknown.png
    - lib/assets/estimated.png
    - lib/assets/material_arrived.png

 # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
